####

GET http://localhost:8080

####

GET http://localhost:8080
Accept-Encoding: gzip

###

POST http://localhost:8080/update
Content-Type: application/json

{
    "id": "coiunter 1",
    "type": "counter",
    "delta": 1
}

###

POST http://localhost:8080/value
Content-Type: application/json

{
    "id": "coiunter 1",
    "type": "counter"
}